<a href="https://colab.research.google.com/github/0715Swathi/MuleSOft_query/blob/main/program8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
iris_dataset = load_iris()
print("Iris Features/Target Names:",iris_dataset.target_names)

Iris Features/Target Names: ['setosa' 'versicolor' 'virginica']


In [ ]:
for i in range(len(iris_dataset.target_names)):
  print("\n[{0}] [{1}]:".format(i,iris_dataset.target_names[i]))
print("Iris data",iris_dataset["data"])
x_train,x_test,y_train,y_test = train_test_split(iris_dataset["data"],iris_dataset['target'],random_state=0)

print('Targets : {}'.format(iris_dataset['target']))
print('X Train:',x_train.shape)
print('X Test:',x_test.shape)
print(' Y Train:',y_train.shape)
print(' Y Test :',y_test.shape)
kn = KNeighborsClassifier(n_neighbors=1)
kn.fit(x_train,y_train)

x_new = np.array([[5,2.9,1,0.2]])
print("X_new is :",x_new)

prediction = kn.predict(x_new)

print('Predicted target names {}'.format(prediction))
print("Predicted feature name {}".format(iris_dataset['target_names'][prediction]))

i=1
x = x_test[i]
x_new = np.array([x])

for i in range(len(x_test)):
  x = x_test[i]
  x_new = np.array([x])
  prediction = kn.predict(x_new)
  print("Actual : {0} {1}, Predicted : {2} {3}".format(y_test[i],iris_dataset['target_names'][y_test[i]],prediction,iris_dataset['target_names'][prediction]))
print(" TEST SCORE[Acuracy] : {:.2f}".format(kn.score(x_test,y_test)))



[0] [setosa]:

[1] [versicolor]:

[2] [virginica]:
Iris data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3